### ISSUE TITLE
Support for Mikro ORM V6

### ISSUE THREAD

**Issue by Tucker-Eric** [TheNightmareX/mikro-orm-soft-delete#5]
Mikro ORM [removed the `@Subscriber()`](https://mikro-orm.io/docs/upgrading-v5-to-v6#removed-subscriber-decorator) decorator requiring manually registering subscribers causing the `SoftDeletableHandlerSubscriber` to break.

Is there plans to support Mikro ORM v6?

**Comment by Char2sGu** [comment]
Hey @Tucker-Eric thanks for letting me know! I do hope to support MikroORM v6, but as I haven't been working on the backend for a while, it could be quite time-consuming for me to pick it up and update the implementation. However, PRs are always welcomed. If there are any PRs to solve this I'll look into that as soon as possible and publish it. :D

**Comment by Tucker-Eric** [comment]
@TheNightmareX Thanks!! PR here https://github.com/TheNightmareX/mikro-orm-soft-delete/pull/6

**Comment by Char2sGu** [comment]
@Tucker-Eric Run `npm i mikro-orm-soft-delete@next` for the latest version.
